# Generated by Django 4.1.5 on 2023-02-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_building_layout_status_section_floorplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='layout',
        ),
        migrations.AlterField(
            model_name='section',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='apartments.building'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apartments.layout'),
            preserve_default=False,
        ),
    ]
