# Generated by Django 4.1.5 on 2023-02-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_section_remove_floorplan_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='layout',
        ),
        migrations.AlterField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building', to='apartments.buildingproject'),
        ),
    ]
