# Generated by Django 4.1.5 on 2023-02-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_remove_floorplan_layout_alter_building_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apartments.layout'),
            preserve_default=False,
        ),
    ]
