# Generated by Django 4.1.5 on 2023-02-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_apartment_floor_alter_apartmentssale_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartments.floorplan'),
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='layout',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apartments.layout'),
            preserve_default=False,
        ),
    ]
