# Generated by Django 4.1.5 on 2023-02-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_remove_apartment_price_apartmentssale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentssale',
            name='coef_floor',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='apartmentssale',
            name='coef_rooms',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=5),
        ),
    ]
